# Highly divisible triangular number
# Problem 12 
# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
  
#  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:
  
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

# This whole method is very slow, and I'm not happy with it.  I'm going to 
# move on while I find a better way

# gives the first triangular number with over N divisors
highly_divisible_triangular_number <- function(N) {
  i <- 1
  sum <- 1
  x <- 1000
  
  while(TRUE){
    factors <- get_factors(sum)
    if (length(factors) > N) {

      return(sum)
    } else {
      i <- i+1
      sum <- sum + i
    }
  }
  
}

# this is a brute force method of finding divisors, surely there is a better way
get_factors <- function(num_to_factor) {
  factors <- rep(TRUE, num_to_factor)
  for (i in 1:num_to_factor) {
    factors[i] <- (num_to_factor %% i == 0)
  }
  return(which(factors))
}

# specific solution
print(highly_divisible_triangular_number(500))
