# Even Fibonacci numbers
# Problem 2 
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
  
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

# specific solution

recent <- 2
previous <- 1
evens_sum <-  2

while (recent < 4000000) {
  new <- recent + previous
  if ( new%%2 == 0) {
    evens_sum <- evens_sum + new
  }
  
  previous <- recent
  recent <- new
  
}

return(evens_sum)


# general solution
# Find the sum of the even valued Fibonacci numbers less than N

N <- 4000000

recent <- 2
previous <- 1
evens_sum <-  2

while (recent < N) {
  new <- recent + previous
  if ( new%%2 == 0) {
    evens_sum <- evens_sum + new
  }
  
  previous <- recent
  recent <- new
  
}

return(evens_sum)